/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import kotlinx.coroutines.*

suspend fun tarefaDemorada() { //função que pode ser pausada (pode-se usar o delay)
    delay(4000L)
    println("Tarefa Concluída")
}

fun main() = runBlocking{ // inicia um escopo de coroutine
    launch { // inicia uma tarefa que acontecerá sem segundo plano
        delay(5000L) //faz com que demore 5 segundos para executar abaixo
        println("Terminei tarefa demorada")
    }
    println("Fim do Programa") // executa imediatamente

    println("Iniciando")
    tarefaDemorada() // com suspend ele não acontecerá em paralelo
    println("Fim")
}
