/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun meuNome(nome: String = "juca", sobrenome: String = "bala") : String {
    return "$nome $sobrenome"
}

fun saudacaoPersonalizada(saudacao: String): (String) -> String {
    return {nome: String -> "$saudacao, $nome"}
}




fun main() {
    meuNome(nome = "hugo", sobrenome = "bonome")
    val aux: (String, String) -> String
    aux = ::meuNome
    val auxInferido = ::meuNome
    print(aux("Hugo", "Bonome"))

    // val funcaoSemParametros: () -> Unit
    // val funcaoSemParametrosERetorno: () -> String
    // val funcaoComDoisParametros: (Int, Int) -> Int

    val saudacaoBomDia = saudacaoPersonalizada("Bom dia!")
    val saudacaoBoaTarde = saudacaoPersonalizada("Boa Tarde!")
    println(saudacaoBomDia("Hugo"))
    println(saudacaoBoaTarde("Juca"))
}
