/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import java.time.LocalDate
import java.time.Month
import java.time.Period

class Pessoa(
    var nome: String = "Desconhecido", // define valor se não for passado (diferentes construtores)
    var dataDascimento: LocalDate = LocalDate.of(1970, Month.JANUARY, 1)
){
    // cria getters e settters se a variável for var

    fun getIdade(): Int {
        return Period.between(dataDascimento, LocalDate.now()).years
    }

    override fun toString(): String {
        return "Nome: $nome, Data de Nascimento: $dataDascimento, Idade: ${getIdade()}"
    }
}

class Carro {
    var velocidade: Int = 0
        set(value){
            require(value >= 0) {"Velocidade não pode ser negativa"}
            field = value // field equivale ao "this.velocidade"
        }
        get(){
            return (field * 0.621371).toInt()
        }

    override fun toString(): String {
        return "A velocidade atual do carro é: $velocidade"
    }
}

fun main() {0
    var pessoa: Pessoa = Pessoa("hugo", LocalDate.of(2003, Month.DECEMBER, 29) )
    println(pessoa)
    pessoa.nome = "Bonome"

    var carro: Carro = Carro()
    carro.velocidade = 100
    println(carro)

    var cachorroA: Cachorro = Cachorro("ted")
    println(cachorroA.fazerSom())

}
